version: '3' # docker-compose version
services:
  #If you need replicas of the containers, copy and past. At this moment,
  #DockerComposeV2's "replica" does not work as DockerComposeV1's
  frontend:
    container_name: facturero-web
    build:
      context: ./facturero-web
      dockerfile: ./Dockerfile
    expose:
      - "4200"
    ports:
      - "4200:80"
    depends_on:
      - backend  
  backend:
    container_name: facturero-api
    build:
      context: ./facturero-api
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    container_name: facturero-db
    image: mongo:8.0
    volumes:
      - mongodb-vol:/data/db
      - ./mongodb-data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${mongo_root_password}
      - MONGO_INITDB_DATABASE= facturacion

volumes:
    mongodb-vol:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${mongo_data_path}
        name: mongodb_volume