services:
  #If you need replicas of the containers, copy and past. At this moment,
  #DockerComposeV2's "replica" does not work as DockerComposeV1's
  frontend:
    container_name: angularfrontend
    build:
      context: ./facturer-web
      dockerfile: ./Dockerfile
  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - backend
  backend:
    container_name: nodebackend
    build:
      context: ./facturero-api
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo:8.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Test2025