FROM node:lts-slim AS build
WORKDIR /src
RUN npm install -g @angular/cli@15

COPY package*.json ./
RUN npm ci

COPY . ./
RUN ng build --configuration=production

FROM nginx:stable AS final
EXPOSE 80
COPY --from=build src/dist/facturero-web  /usr/share/nginx/html